name: resmfn
channels:
  - pytorch
  - iopath
  - fvcore
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2020.07
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _libgcc_mutex=0.1
  - aiohttp=3.7.0
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-navigator=1.10.0
  - anaconda-project=0.8.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - asn1crypto=1.4.0
  - astroid=2.4.2
  - astropy=4.0.2
  - async-timeout=3.0.1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.4
  - babel=2.8.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.9.3
  - bitarray=1.6.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - blosc=1.20.1
  - bokeh=2.2.3
  - boto=2.49.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.8
  - cairo=1.14.12
  - cffi=1.14.3
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - clyent=1.2.2
  - colorama=0.4.4
  - conda=4.12.0
  - conda-build=3.20.5
  - conda-env=2.6.0
  - conda-package-handling=1.7.3
  - conda-verify=3.4.2
  - contextlib2=0.6.0.post1
  - cryptography=3.1.1
  - cudatoolkit=10.2.89
  - curl=7.71.1
  - cycler=0.10.0
  - cython=0.29.21
  - cytoolz=0.11.0
  - dask=2.30.0
  - dask-core=2.30.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - distributed=2.30.1
  - docutils=0.16
  - easydict=1.9
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.10
  - fastcache=1.1.0
  - ffmpeg=4.2.2
  - filelock=3.0.12
  - flake8=3.8.4
  - flask=1.1.2
  - fontconfig=2.13.0
  - freetype=2.10.4
  - fribidi=1.0.10
  - fsspec=0.8.3
  - future=0.18.2
  - fvcore=0.1.5.post20210915
  - gdown=4.4.0
  - get_terminal_size=1.0.0
  - gevent=20.9.0
  - glib=2.66.1
  - glob2=0.7
  - gmp=6.1.2
  - gmpy2=2.0.8
  - gnutls=3.6.15
  - graphite2=1.3.14
  - greenlet=0.4.17
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - harfbuzz=2.4.0
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.1
  - icu=58.2
  - idna=2.10
  - imageio=2.13.1
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - intervaltree=3.1.0
  - iopath=0.1.9
  - ipdb=0.13.9
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=5.6.4
  - itsdangerous=1.1.0
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.17.1
  - jeepney=0.5.0
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - keyring=21.4.0
  - kiwisolver=1.3.0
  - krb5=1.18.2
  - lame=3.100
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libarchive=3.4.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libidn2=2.3.1
  - liblapack=3.8.0
  - liblief=0.10.1
  - libllvm10=10.0.1
  - libllvm9=9.0.1
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtasn1=4.16.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvpx=1.7.0
  - libxcb=1.14
  - libxml2=2.9.10
  - libxslt=1.1.34
  - llvmlite=0.34.0
  - locket=0.2.0
  - lxml=4.6.1
  - lz4-c=1.9.2
  - lzo=2.10
  - markdown=3.3.4
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mock=4.0.2
  - more-itertools=8.6.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.1.0
  - msgpack-python=1.0.0
  - multidict=4.7.5
  - multipledispatch=0.6.0
  - navigator-updater=0.2.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.2
  - nettle=3.7.3
  - networkx=2.5
  - ninja=1.10.2
  - nltk=3.5
  - nose=1.3.7
  - notebook=6.1.4
  - numba=0.51.2
  - numexpr=2.7.1
  - numpy-base=1.19.2
  - numpydoc=1.1.0
  - olefile=0.46
  - openh264=2.1.0
  - openpyxl=3.0.5
  - openssl=1.1.1h
  - packaging=20.4
  - pandoc=2.11
  - pandocfilters=1.4.3
  - pango=1.45.3
  - parso=0.7.0
  - partd=1.1.0
  - patchelf=0.12
  - path=15.0.0
  - path.py=12.5.0
  - pathlib2=2.3.5
  - pathtools=0.1.2
  - patsy=0.5.1
  - pcre=8.44
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pixman=0.40.0
  - pkginfo=1.6.1
  - pluggy=0.13.1
  - ply=3.11
  - portalocker=2.4.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - psutil=5.7.2
  - ptyprocess=0.6.0
  - py=1.9.0
  - py-lief=0.10.1
  - pyasn1=0.4.8
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycurl=7.43.0.6
  - pydocstyle=5.1.1
  - pyflakes=2.2.0
  - pygments=2.7.2
  - pyjwt=2.0.1
  - pylint=2.6.0
  - pyodbc=4.0.30
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.1.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.35.1
  - python-libarchive-c=2.9
  - python_abi=3.8
  - pytorch=1.9.0
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyxdg=0.27
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qdarkstyle=2.8.1
  - qt=5.9.7
  - qtawesome=1.0.1
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - regex=2020.10.15
  - requests=2.24.0
  - ripgrep=12.1.1
  - rope=0.18.0
  - rtree=0.9.4
  - ruamel_yaml=0.15.87
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scikit-video=1.1.11
  - scipy=1.5.2
  - seaborn=0.11.0
  - secretstorage=3.1.2
  - send2trash=1.5.0
  - setuptools=50.3.1
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.13
  - six=1.15.0
  - snappy=1.1.8
  - snowballstemmer=2.0.0
  - sortedcollections=1.2.1
  - sortedcontainers=2.2.2
  - soupsieve=2.0.1
  - sphinx=3.2.1
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sphinxcontrib-websupport=1.2.4
  - spyder=4.1.5
  - spyder-kernels=1.9.4
  - sqlalchemy=1.3.20
  - sqlite=3.33.0
  - statsmodels=0.12.0
  - sympy=1.6.2
  - tabulate=0.8.9
  - tbb=2020.3
  - tblib=1.7.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toml=0.10.1
  - toolz=0.11.1
  - torchaudio=0.9.0
  - torchfile=0.1.0
  - torchvision=0.10.0
  - tornado=6.0.4
  - tqdm=4.63.1
  - trimesh=3.10.7
  - typing_extensions=3.7.4.3
  - ujson=4.0.1
  - unicodecsv=0.14.1
  - unixodbc=2.3.9
  - urllib3=1.25.11
  - visdom=0.1.8.9
  - watchdog=0.10.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.2
  - werkzeug=1.0.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - wurlitzer=2.0.1
  - x264=1!157.20191217
  - xlrd=1.2.0
  - xlsxwriter=1.3.7
  - xlwt=1.3.0
  - xmltodict=0.12.0
  - xz=5.2.5
  - yacs=0.1.8
  - yaml=0.2.5
  - yapf=0.30.0
  - yarl=1.6.3
  - zeromq=4.3.3
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.1.2
  - zstd=1.4.5
  - pip:
    - absl-py==0.13.0
    - blessings==1.7
    - cachetools==4.2.2
    - certifi==2021.10.8
    - debugpy==1.5.1
    - dill==0.3.4
    - dm-haiku==0.0.7.dev0
    - flatbuffers==2.0
    - flow-vis==0.1
    - fonttools==4.28.3
    - geomstats==2.3.1
    - google-auth==1.33.0
    - google-auth-oauthlib==0.4.4
    - googleapis-common-protos==1.55.0
    - gpustat==0.6.0
    - grpcio==1.38.1
    - importlib-resources==5.4.0
    - ipykernel==6.5.0
    - ipython==7.29.0
    - jax==0.3.1
    - jaxlib==0.3.0+cuda11.cudnn82
    - jmp==0.0.2
    - jupyterlab-widgets==1.0.0
    - kornia==0.5.5
    - lpips==0.1.4
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - nglview==3.0.3
    - numpy==1.22.3
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.1
    - opencv-python==4.5.3.56
    - opt-einsum==3.3.0
    - pandas==1.3.5
    - pip==22.0.4
    - promise==2.3
    - protobuf==3.17.3
    - pyasn1-modules==0.2.8
    - pyfftw==0.13.0
    - pymcubes==0.1.2
    - pyro-api==0.1.2
    - pyro-ppl==1.8.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow-datasets==4.5.2
    - tensorflow-metadata==1.7.0
    - termcolor==1.1.0
    - torch-scatter==2.0.7
    - torch-sparse==0.6.10
    - torchdiffeq==0.2.2
    - torchmeta==1.8.0
    - traitlets==5.1.1
